"""add notification campaign models

Revision ID: 0328a3f13381
Revises: 1f60148571ae
Create Date: 2026-03-06 12:04:48.959549

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0328a3f13381'
down_revision = '1f60148571ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject_override', sa.String(length=255), nullable=True),
    sa.Column('content_override', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.String(length=50), nullable=False),
    sa.Column('target_segment_id', sa.Integer(), nullable=True),
    sa.Column('specific_user_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('recipient_ids_snapshot', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_segment_id'], ['user_segments.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_campaigns_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_target_audience'), ['target_audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_target_segment_id'), ['target_segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_campaigns_updated_by_user_id'), ['updated_by_user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_foreign_key(None, 'notification_campaigns', ['campaign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_campaign_id'))
        batch_op.drop_column('campaign_id')

    with op.batch_alter_table('notification_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_updated_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_template_id'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_target_segment_id'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_target_audience'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_channel'))
        batch_op.drop_index(batch_op.f('ix_notification_campaigns_celery_task_id'))

    op.drop_table('notification_campaigns')
    # ### end Alembic commands ###
