"""driver cash active sessions

Revision ID: c8f8f9b6adf5
Revises: b9d1e3f7a2c5
Create Date: 2026-05-13 15:43:21.740030

Rollback strategy:
    downgrade() removes the active-session indexes and new warning/activity
    columns, then restores the legacy driver/date unique constraint. It is only
    safe before drivers create multiple same-day sessions; the data backfill
    that unblocks legacy overdue sessions and resolves duplicate active sessions
    is forward-only and exact restoration requires a backup.

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8f8f9b6adf5"
down_revision = "b9d1e3f7a2c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cash_collection_events", schema=None) as batch_op:
        batch_op.create_index(
            "idx_cash_collection_events_session_occurred", ["driver_cash_session_id", "occurred_at"], unique=False
        )

    with op.batch_alter_table("driver_cash_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("warning_due_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("last_cash_activity_at", sa.DateTime(timezone=True), nullable=True))

    op.execute(
        sa.text(
            """
        UPDATE driver_cash_sessions
        SET
            warning_due_at = COALESCE(warning_due_at, session_started_at + INTERVAL '7 days'),
            submission_due_at = COALESCE(submission_due_at, session_started_at + INTERVAL '7 days')
        WHERE session_started_at IS NOT NULL
          AND status IN ('open', 'overdue')
        """
        )
    )
    op.execute(
        sa.text(
            """
        UPDATE driver_cash_sessions AS session
        SET last_cash_activity_at = events.last_cash_activity_at
        FROM (
            SELECT driver_cash_session_id, MAX(occurred_at) AS last_cash_activity_at
            FROM cash_collection_events
            WHERE driver_cash_session_id IS NOT NULL
              AND voided_at IS NULL
              AND amount > 0
            GROUP BY driver_cash_session_id
        ) AS events
        WHERE session.id = events.driver_cash_session_id
        """
        )
    )
    op.execute(
        sa.text(
            """
        UPDATE driver_cash_sessions
        SET blocked_from_cod = FALSE,
            block_reason = NULL
        WHERE block_reason = 'reconciliation_overdue'
          AND COALESCE(declared_variance, 0) = 0
          AND COALESCE(verified_variance, 0) = 0
        """
        )
    )
    op.execute(
        sa.text(
            """
        WITH ranked AS (
            SELECT
                id,
                ROW_NUMBER() OVER (
                    PARTITION BY driver_user_id
                    ORDER BY
                        CASE
                            WHEN COALESCE(gross_cash_collected, 0) > 0
                              OR COALESCE(expected_cash_on_hand, 0) > 0
                              OR last_cash_activity_at IS NOT NULL
                            THEN 1 ELSE 0
                        END DESC,
                        COALESCE(last_cash_activity_at, session_started_at, created_at) DESC,
                        id DESC
                ) AS active_rank
            FROM driver_cash_sessions
            WHERE status IN ('open', 'overdue')
        )
        UPDATE driver_cash_sessions AS session
        SET
            status = CASE
                WHEN session.blocked_from_cod IS TRUE
                  OR COALESCE(session.declared_variance, 0) <> 0
                  OR COALESCE(session.verified_variance, 0) <> 0
                THEN 'mismatch'::driver_cash_session_status
                ELSE 'resolved'::driver_cash_session_status
            END,
            session_ended_at = COALESCE(session.session_ended_at, NOW()),
            resolution_notes = COALESCE(
                session.resolution_notes,
                'Closed by active-session migration; newer active session retained.'
            ),
            resolution_reason_code = COALESCE(session.resolution_reason_code, 'clerical_correction'),
            resolution_metadata = (
                COALESCE(session.resolution_metadata, '{}'::json)::jsonb
                || jsonb_build_object('active_session_migration', TRUE, 'migrated_at', NOW())
            )::json
        FROM ranked
        WHERE session.id = ranked.id
          AND ranked.active_rank > 1
        """
        )
    )
    op.execute(
        sa.text(
            """
        UPDATE driver_cash_sessions
        SET status = 'overdue'::driver_cash_session_status,
            blocked_from_cod = FALSE,
            block_reason = NULL
        WHERE status = 'open'
          AND submitted_at IS NULL
          AND COALESCE(gross_cash_collected, 0) > 0
          AND warning_due_at <= NOW()
        """
        )
    )

    with op.batch_alter_table("driver_cash_sessions", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_driver_cash_sessions_driver_date"), type_="unique")
        batch_op.create_index(
            "idx_driver_cash_sessions_driver_started", ["driver_user_id", "session_started_at"], unique=False
        )
        batch_op.create_index("idx_driver_cash_sessions_session_ended", ["session_ended_at"], unique=False)
        batch_op.create_index("idx_driver_cash_sessions_status_started", ["status", "session_started_at"], unique=False)
        batch_op.create_index("idx_driver_cash_sessions_status_warning", ["status", "warning_due_at"], unique=False)
        batch_op.create_index("idx_driver_cash_sessions_warning_due", ["warning_due_at"], unique=False)
        batch_op.create_index(
            "uq_driver_cash_sessions_driver_active",
            ["driver_user_id"],
            unique=True,
            postgresql_where=sa.text("status IN ('open', 'overdue')"),
            sqlite_where=sa.text("status IN ('open', 'overdue')"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("driver_cash_sessions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_driver_cash_sessions_driver_active",
            postgresql_where=sa.text("status IN ('open', 'overdue')"),
            sqlite_where=sa.text("status IN ('open', 'overdue')"),
        )
        batch_op.drop_index("idx_driver_cash_sessions_warning_due")
        batch_op.drop_index("idx_driver_cash_sessions_status_warning")
        batch_op.drop_index("idx_driver_cash_sessions_status_started")
        batch_op.drop_index("idx_driver_cash_sessions_session_ended")
        batch_op.drop_index("idx_driver_cash_sessions_driver_started")
        batch_op.create_unique_constraint(
            batch_op.f("uq_driver_cash_sessions_driver_date"),
            ["driver_user_id", "business_date"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.drop_column("last_cash_activity_at")
        batch_op.drop_column("warning_due_at")

    with op.batch_alter_table("cash_collection_events", schema=None) as batch_op:
        batch_op.drop_index("idx_cash_collection_events_session_occurred")

    # ### end Alembic commands ###
