"""Add is_system_reward to loyalty_rewards

Revision ID: 53ff118bbf09
Revises: 2b9b22aff258
Create Date: 2026-01-19 16:30:36.079958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ff118bbf09'
down_revision = '2b9b22aff258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with a server default for existing rows
    with op.batch_alter_table('loyalty_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system_reward', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Remove the server default after migration (column will still be NOT NULL with default in model)
    with op.batch_alter_table('loyalty_rewards', schema=None) as batch_op:
        batch_op.alter_column('is_system_reward', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_rewards', schema=None) as batch_op:
        batch_op.drop_column('is_system_reward')

    # ### end Alembic commands ###
