"""Add paid_at column to payments table

Revision ID: 73c13bd36c4c
Revises: a1b2c3d4e5f6
Create Date: 2025-12-25 16:58:13.882360

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73c13bd36c4c"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credit_cards", schema=None) as batch_op:
        batch_op.alter_column(
            "verification_attempts", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("0")
        )
        batch_op.alter_column(
            "payme_recurrent", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("false")
        )

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_column("paid_at")

    with op.batch_alter_table("credit_cards", schema=None) as batch_op:
        batch_op.alter_column(
            "payme_recurrent", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("false")
        )
        batch_op.alter_column(
            "verification_attempts", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("0")
        )

    # ### end Alembic commands ###
