"""Add order_sequences table for new order number format

Revision ID: 76cc9da9c268
Revises: 73c13bd36c4c
Create Date: 2026-01-05 18:16:40.102186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cc9da9c268'
down_revision = '73c13bd36c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_prefix', sa.String(length=2), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_prefix', 'year', name='uq_order_sequences_prefix_year')
    )
    with op.batch_alter_table('order_sequences', schema=None) as batch_op:
        batch_op.create_index('idx_order_sequences_prefix_year', ['source_prefix', 'year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_sequences', schema=None) as batch_op:
        batch_op.drop_index('idx_order_sequences_prefix_year')

    op.drop_table('order_sequences')
    # ### end Alembic commands ###
