"""drop_driver_bottle_loads_table

Revision ID: 9ef3918623ff
Revises: d4753e242cd4
Create Date: 2026-04-16 12:23:55.316482

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9ef3918623ff"
down_revision = "d4753e242cd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("corporate_prepayment_legacy_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_corporate_prepayment_legacy_snapshots_contract"))
        batch_op.drop_index(batch_op.f("ix_corporate_prepayment_legacy_snapshots_account_id"))
        batch_op.drop_index(batch_op.f("ix_corporate_prepayment_legacy_snapshots_contract_id"))

    op.drop_table("corporate_prepayment_legacy_snapshots")
    with op.batch_alter_table("driver_bottle_loads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_driver_bottle_loads_driver_date"))

    op.drop_table("driver_bottle_loads")
    with op.batch_alter_table("bottle_balances", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("bottle_fines", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("bottle_ledger", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.create_index(batch_op.f("ix_bottle_ledger_event_type"), ["event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_bottle_ledger_order_id"), ["order_id"], unique=False)

    with op.batch_alter_table("corporate_contracts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("corporate_contracts_contract_number_key"), type_="unique")

    with op.batch_alter_table("driver_bottle_session_orders", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.create_index(batch_op.f("ix_driver_bottle_session_orders_order_id"), ["order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_driver_bottle_session_orders_session_id"), ["session_id"], unique=False)

    with op.batch_alter_table("driver_bottle_sessions", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_constraint(batch_op.f("driver_bottle_sessions_session_ref_key"), type_="unique")
        batch_op.create_index(batch_op.f("ix_driver_bottle_sessions_driver_user_id"), ["driver_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_driver_bottle_sessions_session_ref"), ["session_ref"], unique=True)
        batch_op.create_index(batch_op.f("ix_driver_bottle_sessions_status"), ["status"], unique=False)

    with op.batch_alter_table("driver_bottle_transfers", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_constraint(batch_op.f("driver_bottle_transfers_transfer_ref_key"), type_="unique")
        batch_op.create_index(
            batch_op.f("ix_driver_bottle_transfers_receiver_driver_id"), ["receiver_driver_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_driver_bottle_transfers_receiver_session_id"), ["receiver_session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_driver_bottle_transfers_sender_driver_id"), ["sender_driver_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_driver_bottle_transfers_sender_session_id"), ["sender_session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_driver_bottle_transfers_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_driver_bottle_transfers_transfer_ref"), ["transfer_ref"], unique=True)

    with op.batch_alter_table("product_tryouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_tryouts_tryout_number"))
        batch_op.create_index(batch_op.f("ix_product_tryouts_tryout_number"), ["tryout_number"], unique=True)
        batch_op.create_index(batch_op.f("ix_product_tryouts_outcome"), ["outcome"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_tryouts_source"), ["source"], unique=False)

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("idx_products_search_trgm"),
            postgresql_ops={
                "((((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(sku, ''::character varying)::text)": "gin_trgm_ops"
            },
            postgresql_using="gin",
        )

    with op.batch_alter_table("tax_committee_api_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("tryout_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tryout_tasks_completed_by_user_id"), ["completed_by_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tryout_tasks_created_by_user_id"), ["created_by_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tryout_tasks_due_at"), ["due_at"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_user_type"), ["user_type"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_user_type"))

    with op.batch_alter_table("tryout_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tryout_tasks_due_at"))
        batch_op.drop_index(batch_op.f("ix_tryout_tasks_created_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_tryout_tasks_completed_by_user_id"))

    with op.batch_alter_table("tax_committee_api_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_products_search_trgm"),
            [
                sa.literal_column(
                    "((((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(sku, ''::character varying)::text)"
                )
            ],
            unique=False,
            postgresql_ops={
                "((((COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(sku, ''::character varying)::text)": "gin_trgm_ops"
            },
            postgresql_using="gin",
        )

    with op.batch_alter_table("product_tryouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_tryouts_source"))
        batch_op.drop_index(batch_op.f("ix_product_tryouts_outcome"))
        batch_op.drop_index(batch_op.f("ix_product_tryouts_tryout_number"))
        batch_op.create_index(batch_op.f("ix_product_tryouts_tryout_number"), ["tryout_number"], unique=False)

    with op.batch_alter_table("driver_bottle_transfers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_driver_bottle_transfers_transfer_ref"))
        batch_op.drop_index(batch_op.f("ix_driver_bottle_transfers_status"))
        batch_op.drop_index(batch_op.f("ix_driver_bottle_transfers_sender_session_id"))
        batch_op.drop_index(batch_op.f("ix_driver_bottle_transfers_sender_driver_id"))
        batch_op.drop_index(batch_op.f("ix_driver_bottle_transfers_receiver_session_id"))
        batch_op.drop_index(batch_op.f("ix_driver_bottle_transfers_receiver_driver_id"))
        batch_op.create_unique_constraint(
            batch_op.f("driver_bottle_transfers_transfer_ref_key"),
            ["transfer_ref"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("driver_bottle_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_driver_bottle_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_driver_bottle_sessions_session_ref"))
        batch_op.drop_index(batch_op.f("ix_driver_bottle_sessions_driver_user_id"))
        batch_op.create_unique_constraint(
            batch_op.f("driver_bottle_sessions_session_ref_key"), ["session_ref"], postgresql_nulls_not_distinct=False
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("driver_bottle_session_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_driver_bottle_session_orders_session_id"))
        batch_op.drop_index(batch_op.f("ix_driver_bottle_session_orders_order_id"))
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("corporate_contracts", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("corporate_contracts_contract_number_key"),
            ["contract_number"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("bottle_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bottle_ledger_order_id"))
        batch_op.drop_index(batch_op.f("ix_bottle_ledger_event_type"))
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("bottle_fines", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("bottle_balances", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    op.create_table(
        "driver_bottle_loads",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("driver_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("load_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("bottles_loaded", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.Column("bottles_delivered", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.Column("bottles_collected", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.Column(
            "bottles_returned_to_warehouse",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("discrepancy", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.Column("reconciled", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
        sa.Column("reconciled_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("reconciled_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["driver_user_id"], ["users.id"], name=op.f("driver_bottle_loads_driver_user_id_fkey")),
        sa.ForeignKeyConstraint(["reconciled_by"], ["users.id"], name=op.f("driver_bottle_loads_reconciled_by_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("driver_bottle_loads_pkey")),
        sa.UniqueConstraint(
            "driver_user_id",
            "load_date",
            name=op.f("uq_driver_bottle_load_date"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    with op.batch_alter_table("driver_bottle_loads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_driver_bottle_loads_driver_date"), ["driver_user_id", "load_date"], unique=False
        )

    op.create_table(
        "corporate_prepayment_legacy_snapshots",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("contract_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("prepaid_units", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
        sa.Column("reserved_units", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
        sa.Column("consumed_units", sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
        sa.Column("legacy_ledger_entries_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("migrated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["corporate_prepayment_accounts.id"],
            name=op.f("corporate_prepayment_legacy_snapshots_account_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["corporate_contracts.id"],
            name=op.f("corporate_prepayment_legacy_snapshots_contract_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("corporate_prepayment_legacy_snapshots_pkey")),
        sa.UniqueConstraint(
            "account_id",
            name=op.f("uq_corporate_prepayment_legacy_snapshot_account"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    with op.batch_alter_table("corporate_prepayment_legacy_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_corporate_prepayment_legacy_snapshots_contract_id"), ["contract_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_corporate_prepayment_legacy_snapshots_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_corporate_prepayment_legacy_snapshots_contract"), ["contract_id"], unique=False
        )

    # ### end Alembic commands ###
