"""add orders.tier_discount + ck_orders_tier_discount_nonneg

Revision ID: a1b7c3d9e5f2
Revises: b6d1e8f4a207
Create Date: 2026-08-27 10:00:00.000000

Loyalty tier discounts on COD orders.

Hand-written rather than autogenerated so the CHECK constraint is explicit.
The constraint name and its ``"col" >= 0`` shape copy the five existing
``orders`` guards installed by migration b8e3c9f5d2a4 (subtotal,
discount_amount, delivery_fee, loyalty_discount, total_amount).

No backfill and no pre-flight violation scan: the column does not exist yet,
so every existing row lands on the ``0.00`` server default — which is
correct, those orders were priced before the feature existed.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a1b7c3d9e5f2"
down_revision = "b6d1e8f4a207"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "orders",
        sa.Column(
            "tier_discount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default="0.00",
        ),
    )
    op.create_check_constraint(
        "ck_orders_tier_discount_nonneg",
        "orders",
        '"tier_discount" >= 0',
    )


def downgrade():
    op.drop_constraint(
        "ck_orders_tier_discount_nonneg",
        "orders",
        type_="check",
    )
    op.drop_column("orders", "tier_discount")
