"""Refactor subscription: billing_cycle to ENUM, delivery_time_slot to nullable FK

Revision ID: c4c3e7713eb7
Revises: 06f202673824
Create Date: 2025-12-08 10:09:18.481980

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c4c3e7713eb7"
down_revision = "06f202673824"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # PostgreSQL requires explicit cast for VARCHAR to ENUM conversion
    connection = op.get_bind()

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        # Add new delivery_time_slot_id column
        batch_op.add_column(sa.Column("delivery_time_slot_id", sa.Integer(), nullable=True))

        # Create foreign key
        batch_op.create_foreign_key(
            "fk_subscriptions_delivery_time_slot", "delivery_time_slots", ["delivery_time_slot_id"], ["id"]
        )

        # Drop old delivery_time_slot column
        batch_op.drop_column("delivery_time_slot")

    # Convert billing_cycle from VARCHAR to ENUM using raw SQL (PostgreSQL requires USING clause)
    connection.execute(
        sa.text(
            "ALTER TABLE subscriptions ALTER COLUMN billing_cycle TYPE subscription_frequency USING billing_cycle::subscription_frequency"  # noqa: E501
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        # NOT NULL with no server_default would fail on a non-empty table
        # (existing rows have no value to backfill into the resurrected
        # column). server_default="" backfills existing rows; the default
        # is then dropped below so the column matches its original
        # (pre-c4c3e7713eb7) definition, which had no server_default — the
        # app always supplied a value on insert.
        batch_op.add_column(
            sa.Column(
                "delivery_time_slot",
                sa.VARCHAR(length=20),
                autoincrement=False,
                nullable=False,
                server_default="",
            )
        )
        # ARCH-013: name the FK created in upgrade() so downgrade can drop it.
        batch_op.drop_constraint("fk_subscriptions_delivery_time_slot", type_="foreignkey")
        batch_op.alter_column(
            "billing_cycle",
            existing_type=sa.Enum("daily", "weekly", "biweekly", "monthly", name="subscription_frequency"),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )
        batch_op.drop_column("delivery_time_slot_id")
        batch_op.alter_column("delivery_time_slot", server_default=None)

    # ### end Alembic commands ###
