"""empty message

Revision ID: cea8f329e11e
Revises: 9d04c0e40a2d
Create Date: 2026-02-10 21:45:58.780430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea8f329e11e'
down_revision = '9d04c0e40a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_activity_log', schema=None) as batch_op:
        batch_op.create_index('idx_staff_activity_action', ['action'], unique=False)
        batch_op.create_index('idx_staff_activity_created', ['created_at'], unique=False)
        batch_op.create_index('idx_staff_activity_user', ['user_id'], unique=False)

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_collected', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('delivery_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_concurrent_deliveries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_active_deliveries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_cash_collected', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notifications_muted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by_staff_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_roles', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('staff_bot_state', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('staff_bot_state')
        batch_op.drop_column('staff_roles')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by_staff_id')

    with op.batch_alter_table('delivery_persons', schema=None) as batch_op:
        batch_op.drop_column('notifications_muted')
        batch_op.drop_column('total_cash_collected')
        batch_op.drop_column('current_active_deliveries')
        batch_op.drop_column('max_concurrent_deliveries')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('cash_collected')

    with op.batch_alter_table('staff_activity_log', schema=None) as batch_op:
        batch_op.drop_index('idx_staff_activity_user')
        batch_op.drop_index('idx_staff_activity_created')
        batch_op.drop_index('idx_staff_activity_action')

    op.drop_table('staff_activity_log')
    # ### end Alembic commands ###
