"""Loyalty Overhaul: Add uzs_per_point and streak fields

Revision ID: d28233e7650e
Revises: f8a9b2c3d4e5
Create Date: 2026-01-22 05:09:51.450035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28233e7650e'
down_revision = 'f8a9b2c3d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier_valid_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_streak_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('streak_orders_this_month', sa.Integer(), nullable=True))

    with op.batch_alter_table('loyalty_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uzs_per_point', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_programs', schema=None) as batch_op:
        batch_op.drop_column('uzs_per_point')

    with op.batch_alter_table('loyalty_points', schema=None) as batch_op:
        batch_op.drop_column('streak_orders_this_month')
        batch_op.drop_column('last_streak_update')
        batch_op.drop_column('current_streak')
        batch_op.drop_column('tier_valid_until')

    # ### end Alembic commands ###
