"""Increase card_token column length to 511

Revision ID: ef3ba1878e42
Revises: c4c3e7713eb7
Create Date: 2025-12-24 16:03:28.449977

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef3ba1878e42"
down_revision = "c4c3e7713eb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credit_cards", schema=None) as batch_op:
        batch_op.alter_column(
            "card_token", existing_type=sa.VARCHAR(length=255), type_=sa.String(length=511), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credit_cards", schema=None) as batch_op:
        batch_op.alter_column(
            "card_token", existing_type=sa.String(length=511), type_=sa.VARCHAR(length=255), existing_nullable=False
        )

    # ### end Alembic commands ###
