"""add click fiscalization and marking code schema

Revision ID: f66d4fcce111
Revises: 9e6ea31bb927
Create Date: 2026-03-11 19:03:49.218646

"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = 'f66d4fcce111'
down_revision = '9e6ea31bb927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_fiscal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('spic', sa.String(length=100), nullable=True),
    sa.Column('package_code', sa.String(length=100), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('vat_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fiscalization_enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_marking_codes', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_fiscal_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_product_fiscal_profiles_enabled', ['fiscalization_enabled'], unique=False)
        batch_op.create_index('idx_product_fiscal_profiles_marking_required', ['requires_marking_codes'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_fiscal_profiles_product_id'), ['product_id'], unique=True)

    op.create_table('product_marking_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'used', 'archived', name='product_marking_code_status'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_marking_codes', schema=None) as batch_op:
        batch_op.create_index('idx_product_marking_codes_product_status', ['product_id', 'status'], unique=False)
        batch_op.create_index('idx_product_marking_codes_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_marking_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_marking_codes_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_marking_codes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_marking_codes_status'), ['status'], unique=False)

    op.create_table('payment_fiscalizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_required', 'pending', 'processing', 'completed', 'failed', name='payment_fiscalization_status'), nullable=False),
    sa.Column('provider_name', sa.String(length=32), nullable=False),
    sa.Column('provider_receipt_id', sa.String(length=255), nullable=True),
    sa.Column('provider_receipt_url', sa.String(length=500), nullable=True),
    sa.Column('provider_status', sa.String(length=64), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('receipt_payload', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_fiscalizations', schema=None) as batch_op:
        batch_op.create_index('idx_payment_fiscalizations_provider_receipt', ['provider_receipt_id'], unique=False)
        batch_op.create_index('idx_payment_fiscalizations_status_attempt', ['status', 'last_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_fiscalizations_payment_id'), ['payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_fiscalizations_provider_receipt_id'), ['provider_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_fiscalizations_status'), ['status'], unique=False)

    op.create_table('order_item_marking_code_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('product_marking_code_id', sa.Integer(), nullable=False),
    sa.Column('payment_fiscalization_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('created', 'imported', 'reserved', 'released', 'used', 'archived', 'restored', name='marking_code_ledger_event_type'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['payment_fiscalization_id'], ['payment_fiscalizations.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['product_marking_code_id'], ['product_marking_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item_marking_code_allocations', schema=None) as batch_op:
        batch_op.create_index('idx_order_item_marking_code_allocations_code_created', ['product_marking_code_id', 'created_at'], unique=False)
        batch_op.create_index('idx_order_item_marking_code_allocations_item_created', ['order_item_id', 'created_at'], unique=False)
        batch_op.create_index('idx_order_item_marking_code_allocations_payment_created', ['payment_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_marking_code_allocations_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_marking_code_allocations_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_marking_code_allocations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_marking_code_allocations_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_marking_code_allocations_payment_fiscalization_id'), ['payment_fiscalization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_marking_code_allocations_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_marking_code_allocations_product_marking_code_id'), ['product_marking_code_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'consume_marking_codes',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.alter_column('consume_marking_codes', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('consume_marking_codes')

    with op.batch_alter_table('order_item_marking_code_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_marking_code_allocations_product_marking_code_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_marking_code_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_marking_code_allocations_payment_fiscalization_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_marking_code_allocations_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_marking_code_allocations_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_marking_code_allocations_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_marking_code_allocations_action'))
        batch_op.drop_index('idx_order_item_marking_code_allocations_payment_created')
        batch_op.drop_index('idx_order_item_marking_code_allocations_item_created')
        batch_op.drop_index('idx_order_item_marking_code_allocations_code_created')

    op.drop_table('order_item_marking_code_allocations')
    with op.batch_alter_table('payment_fiscalizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_fiscalizations_status'))
        batch_op.drop_index(batch_op.f('ix_payment_fiscalizations_provider_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_payment_fiscalizations_payment_id'))
        batch_op.drop_index('idx_payment_fiscalizations_status_attempt')
        batch_op.drop_index('idx_payment_fiscalizations_provider_receipt')

    op.drop_table('payment_fiscalizations')
    with op.batch_alter_table('product_marking_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_marking_codes_status'))
        batch_op.drop_index(batch_op.f('ix_product_marking_codes_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_marking_codes_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_product_marking_codes_code'))
        batch_op.drop_index('idx_product_marking_codes_status_created')
        batch_op.drop_index('idx_product_marking_codes_product_status')

    op.drop_table('product_marking_codes')
    with op.batch_alter_table('product_fiscal_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_fiscal_profiles_product_id'))
        batch_op.drop_index('idx_product_fiscal_profiles_marking_required')
        batch_op.drop_index('idx_product_fiscal_profiles_enabled')

    op.drop_table('product_fiscal_profiles')
    # ### end Alembic commands ###
